version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imagecrm
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4:5.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
      - "./docker/servers.json:/pgadmin4/servers.json"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
