definitions:
  dto.CreateReportDTO:
    properties:
      report_id:
        type: string
      url:
        type: string
    required:
    - report_id
    - url
    type: object
  models.Report:
    properties:
      created_at:
        type: string
      id:
        type: string
      report_id:
        type: string
      status:
        type: integer
      url:
        type: string
    required:
    - report_id
    - url
    type: object
host: localhost:3000
info:
  contact: {}
  description: A quickly API setup to evaulate avatar.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Image Evaluate API
  version: "1.0"
paths:
  /report:
    get:
      consumes:
      - application/json
      description: List all reports
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Report'
            type: array
      summary: Get a list of reports id
      tags:
      - report
    post:
      consumes:
      - application/json
      description: Saves a request for avatar evaluate
      parameters:
      - description: Create a report
        in: body
        name: evaluate
        required: true
        schema:
          $ref: '#/definitions/dto.CreateReportDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Report'
            type: array
      summary: Endpoint to save avatar reports
      tags:
      - report
  /report/{id}:
    get:
      consumes:
      - application/json
      description: Get details of report corresponding to the input id
      parameters:
      - description: Report ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Report'
      summary: Get details for a given report id
      tags:
      - report
swagger: "2.0"
